/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all supported achievements */
        get: operations["get-achievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bosses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all bosses */
        get: operations["get-bosses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["get-categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create / Initialize a guild */
        post: operations["create-guild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a guild by ID */
        get: operations["get-guild"];
        /** Update a guild */
        put: operations["update-guild"];
        post?: never;
        /** Delete a guild */
        delete: operations["delete-guild"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/combat-achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get guild combat achievements */
        get: operations["get-guild-combat-achievements"];
        put?: never;
        /** Create a combat achievement for a guild */
        post: operations["create-combat-achievement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/combat-achievements/{ca_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a combat achievement from a guild */
        delete: operations["delete-combat-achievement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/combat-achievements/{ca_name}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a combat achievement */
        post: operations["complete-combat-achievement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the guild's events */
        get: operations["get-events"];
        put?: never;
        /** Register a guild event */
        post: operations["register-event"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the guild's event details */
        get: operations["get-detailed-event"];
        /** Update a guild event */
        put: operations["update-event"];
        post?: never;
        /** Delete a guild event */
        delete: operations["delete-event"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a guild's leaderboard by ID */
        get: operations["get-leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get guild point sources */
        get: operations["get-point-sources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/points/{point_source}/{points}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a guild point source */
        put: operations["update-guild-point-source"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get guild rank tiers */
        get: operations["get-guild-ranks"];
        put?: never;
        /** Create a guild rank tier */
        post: operations["create-guild-rank"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/ranks/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a guild rank tier */
        put: operations["update-guild-rank"];
        post?: never;
        /** Delete a guild rank tier */
        delete: operations["delete-guild-rank"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all guild records */
        get: operations["get-guild-records"];
        put?: never;
        /** Add a new record to guild */
        post: operations["create-record"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/records/id/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a record from guild */
        delete: operations["remove-record"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/records/{boss}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear all records for a boss */
        delete: operations["clear-boss-records"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/records/{boss}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revert top record (delete #1, next best becomes #1) */
        delete: operations["revert-top-record"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/teams/boss/{boss}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a new teammate to record by boss */
        post: operations["add-teammate-by-boss"];
        /** Remove a teammate from record by boss */
        delete: operations["remove-teammate-by-boss"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/teams/id/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a new teammate to record by record ID */
        post: operations["add-teammate-by-record-id"];
        /** Remove a teammate from record by record ID */
        delete: operations["remove-teammate-by-record-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create / Initialize a new user */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/rsn/{rsns}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one or more users by RSN(s) */
        get: operations["get-users-by-rsn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/rsn/{rsn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user by RSN */
        delete: operations["remove-user-by-rsn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/rsn/{rsn}/achievements/{achievement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give an achievement to user by RSN */
        post: operations["give-achievement-by-rsn"];
        /** Remove an achievement from user by RSN */
        delete: operations["remove-achievement-by-rsn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/wom/{wom_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one or more users by WOM ID(s) */
        get: operations["get-users-by-wom"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/wom/{wom_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user by WOM ID */
        delete: operations["remove-user-by-wom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_ids}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one or more users by ID(s) */
        get: operations["get-users-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_ids}/points/custom/{points}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user(s) points with custom amount */
        put: operations["update-points-custom"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_ids}/points/{point_event}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user(s) points by event */
        put: operations["update-points"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a user by User ID */
        delete: operations["remove-user-by-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user achievements */
        get: operations["get-user-achievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/achievements/{achievement}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Give an achievement to user by ID */
        post: operations["give-achievement-by-id"];
        /** Remove an achievement from user by ID */
        delete: operations["remove-achievement-by-id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/combat-achievements/{ca_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant a combat achievement to a user */
        post: operations["give-user-combat-achievement"];
        /** Remove a combat achievement from a user */
        delete: operations["remove-user-combat-achievement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user events */
        get: operations["get-user-events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user records */
        get: operations["get-user-records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/rsns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link an RSN to a user */
        post: operations["create-rsn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/users/{user_id}/rsns/{rsn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove RSN from guild and user */
        delete: operations["remove-rsn"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/wom/competition/{competition_id}/cutoff/{cutoff}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Handle WOM competition end */
        get: operations["end-competition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/wom/winners/{competition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get competition winners */
        get: operations["competition-winners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guilds/{guild_id}/wom/winners/{competition_id}/team/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get competition winners by team name */
        get: operations["competition-team-position"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/value-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all value types */
        get: operations["get-value-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Achievement: {
            discord_icon: string;
            name: string;
            /** Format: int32 */
            order: number;
            thumbnail: string;
        };
        Boss: {
            category: string;
            display_name: string;
            name: string;
            solo: boolean;
            value_type: string;
        };
        Category: {
            name: string;
            /** Format: int32 */
            order: number;
            thumbnail: components["schemas"]["Text"];
        };
        CompetitionResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CompetitionResponse.json
             */
            readonly $schema?: string;
            accounts: string[] | null;
            /** Format: int64 */
            cutoff: number;
            /** Format: int64 */
            participant_count: number;
            participants: components["schemas"]["DetailedUser"][] | null;
            /** Format: int64 */
            points_given: number;
            title: string;
        };
        CompleteCombatAchievementBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CompleteCombatAchievementBody.json
             */
            readonly $schema?: string;
            user_ids: string[] | null;
        };
        CreateCombatAchievementBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateCombatAchievementBody.json
             */
            readonly $schema?: string;
            name: string;
            point_source: string;
        };
        CreateGuildRankBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateGuildRankBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            display_order: number;
            icon?: string;
            /** Format: int64 */
            min_points: number;
            name: string;
            role_id?: string;
        };
        CreateRsnBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateRsnBody.json
             */
            readonly $schema?: string;
            rsn: string;
        };
        CreateUserBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateUserBody.json
             */
            readonly $schema?: string;
            rsn: string;
            user_id: string;
        };
        CreateUserRow: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateUserRow.json
             */
            readonly $schema?: string;
            guild_id: string;
            /** Format: int32 */
            points: number;
            rsn: string;
            user_id: string;
            wom_id: string;
        };
        DetailedEvent: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DetailedEvent.json
             */
            readonly $schema?: string;
            participations: components["schemas"]["EventParticipation"][] | null;
        };
        DetailedUser: {
            achievements: components["schemas"]["UserAchievement"][] | null;
            combat_achievements: components["schemas"]["UserCombatAchievement"][] | null;
            events: components["schemas"]["UserEvent"][] | null;
            guild_id: string;
            /** Format: int64 */
            points: number;
            /** Format: int64 */
            rank: number;
            records: components["schemas"]["UserRecord"][] | null;
            rsns: components["schemas"]["UserRsn"][] | null;
            tier?: components["schemas"]["UserTier"];
            user_id: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Event: {
            guild_id: string;
            name: string;
            /** Format: int32 */
            position_cutoff: number;
            solo: boolean;
            wom_id: string;
        };
        EventParticipation: {
            /** Format: int64 */
            placement: number;
            user_id: string;
        };
        GetGuildCombatAchievementsRow: {
            name: string;
            point_source: string;
            point_source_display_name: string;
            /** Format: int32 */
            points: number;
        };
        GetGuildPointSourcesRow: {
            name: string;
            /** Format: int32 */
            points: number;
            source: string;
        };
        GetUserAchievementsRow: {
            discord_icon: string;
            name: string;
            thumbnail: string;
        };
        GetUserEventsRow: {
            event_id: string;
            guild_id: string;
            name: string;
            /** Format: int32 */
            placement: number;
            /** Format: int32 */
            position_cutoff: number;
            solo: boolean;
            user_id: string;
        };
        GuildBoss: {
            category: string;
            display_name: string;
            name: string;
            solo: boolean;
            value_type: string;
        };
        GuildBossEntry: {
            boss: string;
            category: string;
            guild_id: string;
        };
        GuildCategory: {
            name: string;
            /** Format: int32 */
            order: number;
            thumbnail: string;
        };
        GuildCategoryEntry: {
            category: string;
            guild_id: string;
            message_id: string;
        };
        GuildCategoryMessage: {
            category: string;
            message_id: string;
        };
        GuildRankResponse: {
            /** Format: int32 */
            display_order: number;
            icon?: string;
            /** Format: int32 */
            min_points: number;
            name: string;
            role_id?: string;
        };
        GuildRecord: {
            boss_name: string;
            date: string;
            guild_id: string;
            /** Format: int64 */
            position: number;
            /** Format: int32 */
            record_id: number;
            /** Format: int32 */
            value: number;
        };
        GuildResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GuildResponse.json
             */
            readonly $schema?: string;
            bosses?: components["schemas"]["GuildBoss"][] | null;
            categories?: components["schemas"]["GuildCategory"][] | null;
            guild_bosses?: components["schemas"]["GuildBossEntry"][] | null;
            guild_categories?: components["schemas"]["GuildCategoryEntry"][] | null;
            guild_id: string;
            mod_channel_id: string | null;
            /** Format: double */
            multiplier: number;
            pb_channel_id: string | null;
            /** Format: int32 */
            position_count: number;
            /** Format: int64 */
            record_count: number;
            records?: components["schemas"]["GuildRecord"][] | null;
            teammates?: components["schemas"]["GuildTeammate"][] | null;
            /** Format: int64 */
            user_count: number;
        };
        GuildTeammate: {
            guild_id: string;
            /** Format: int32 */
            record_id: number;
            user_id: string;
        };
        InputEvent: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InputEvent.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            event_id: number;
            /** Format: int64 */
            position_cutoff?: number;
            team_names?: string[] | null;
        };
        InputGuild: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InputGuild.json
             */
            readonly $schema?: string;
            guild_id: string;
        };
        InputRecord: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InputRecord.json
             */
            readonly $schema?: string;
            boss_name: string;
            user_ids: string[] | null;
            /** Format: int64 */
            value: number;
        };
        InputTeammate: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/InputTeammate.json
             */
            readonly $schema?: string;
            guild_id: string;
            user_id: string;
        };
        LeaderboardUser: {
            guild_id: string;
            /** Format: int32 */
            points: number;
            rsns: components["schemas"]["UserRsn"][] | null;
            user_id: string;
        };
        Numeric: {
            /** Format: int32 */
            Exp: number;
            /** Format: int32 */
            InfinityModifier: number;
            Int: string | null;
            NaN: boolean;
            Valid: boolean;
        };
        PbUpdate: {
            category_messages: components["schemas"]["GuildCategoryMessage"][] | null;
            channel_id: string;
        };
        RecordResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RecordResponse.json
             */
            readonly $schema?: string;
            boss_name: string;
            /** Format: int64 */
            position?: number;
            /** Format: int64 */
            record_id: number;
            /** Format: int64 */
            value: number;
            /** Format: int64 */
            value_old: number;
        };
        RecordTeammate: {
            guild_id: string;
            user_id: string;
        };
        Text: {
            String: string;
            Valid: boolean;
        };
        UpdateEventInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateEventInputBody.json
             */
            readonly $schema?: string;
            name: string;
            position_cutoff: components["schemas"]["Numeric"];
            solo: boolean;
        };
        UpdateGuildBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateGuildBody.json
             */
            readonly $schema?: string;
            mod_channel_id?: string;
            /** Format: double */
            multiplier?: number;
            pb_update?: components["schemas"]["PbUpdate"];
            /** Format: int64 */
            position_count?: number;
        };
        UpdateGuildRankBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateGuildRankBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            display_order?: number;
            icon?: string;
            /** Format: int64 */
            min_points?: number;
            role_id?: string;
        };
        UpdatePointsByEventRow: {
            /** Format: int32 */
            given_points: number;
            guild_id: string;
            /** Format: int32 */
            points: number;
            user_id: string;
        };
        UpdatePointsCustomRow: {
            /** Format: int32 */
            given_points: number;
            guild_id: string;
            /** Format: int32 */
            points: number;
            user_id: string;
        };
        UserAchievement: {
            discord_icon: string;
            name: string;
            /** Format: int32 */
            order: number;
            thumbnail: string;
        };
        UserCombatAchievement: {
            name: string;
        };
        UserEvent: {
            guild_id: string;
            name: string;
            /** Format: int32 */
            placement: number;
            /** Format: int32 */
            position_cutoff: number;
            solo: boolean;
            wom_id: string;
        };
        UserRecord: {
            boss_name: string;
            category: string;
            /** Format: date-time */
            date: string;
            display_name: string;
            /** Format: int32 */
            record_id: number;
            solo: boolean;
            team: components["schemas"]["RecordTeammate"][] | null;
            /** Format: int32 */
            value: number;
            value_type: string;
        };
        UserRsn: {
            rsn: string;
            wom_id: string;
        };
        UserTier: {
            /** Format: int32 */
            display_order: number;
            icon?: string;
            /** Format: int32 */
            min_points: number;
            name: string;
            role_id?: string;
        };
        ValueType: {
            higher_is_better: boolean;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Achievement"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-bosses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Boss"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-guild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputGuild"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-guild": {
        parameters: {
            query?: {
                /** @description Fetch detailed guild information */
                detailed?: boolean;
            };
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-guild": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGuildBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-guild": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-guild-combat-achievements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGuildCombatAchievementsRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-combat-achievement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCombatAchievementBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-combat-achievement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Combat Achievement Name */
                ca_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "complete-combat-achievement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Combat Achievement Name */
                ca_name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteCombatAchievementBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePointsByEventRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "register-event": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputEvent"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-detailed-event": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Event WOM ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedEvent"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-event": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Event WOM ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventInputBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-event": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Event WOM ID */
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-leaderboard": {
        parameters: {
            query?: {
                /** @description Maximum number of users to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardUser"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-point-sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetGuildPointSourcesRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-guild-point-source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Point source name */
                point_source: string;
                /** @description New point value */
                points: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-guild-ranks": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildRankResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-guild-rank": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuildRankBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-guild-rank": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Rank name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGuildRankBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-guild-rank": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Rank name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-guild-records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuildResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-record": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputRecord"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-record": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Record ID */
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "clear-boss-records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Boss name */
                boss: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "revert-top-record": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Boss name */
                boss: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-teammate-by-boss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Boss name */
                boss: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputTeammate"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-teammate-by-boss": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Boss name */
                boss: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputTeammate"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-teammate-by-record-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Record ID */
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputTeammate"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-teammate-by-record-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Record ID */
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputTeammate"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateUserRow"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-users-by-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Comma-separated RuneScape Names */
                rsns: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedUser"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-user-by-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description RuneScape Name */
                rsn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "give-achievement-by-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description RuneScape Name */
                rsn: string;
                /** @description Achievement name */
                achievement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-achievement-by-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description RuneScape Name */
                rsn: string;
                /** @description Achievement name */
                achievement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-users-by-wom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Comma-separated WOM IDs */
                wom_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedUser"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-user-by-wom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description WOM ID */
                wom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-users-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Comma-separated User Snowflake IDs */
                user_ids: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailedUser"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-points-custom": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Comma-separated User Snowflake IDs */
                user_ids: string;
                /** @description Points to add */
                points: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePointsCustomRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-points": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description Comma-separated User Snowflake IDs */
                user_ids: string;
                /** @description Point event name */
                point_event: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePointsByEventRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-user-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-achievements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserAchievementsRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "give-achievement-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
                /** @description Achievement name */
                achievement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-achievement-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
                /** @description Achievement name */
                achievement: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "give-user-combat-achievement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
                /** @description Combat Achievement Name */
                ca_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-user-combat-achievement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
                /** @description Combat Achievement Name */
                ca_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserEventsRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-user-records": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRecord"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRsnBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-rsn": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description User Snowflake ID */
                user_id: string;
                /** @description RuneScape Name */
                rsn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "end-competition": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description WOM Competition ID */
                competition_id: number;
                /** @description Minimum score cutoff */
                cutoff: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "competition-winners": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description WOM Competition ID */
                competition_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "competition-team-position": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Guild Snowflake ID */
                guild_id: string;
                /** @description WOM Competition ID */
                competition_id: string;
                /** @description Team name */
                team: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-value-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueType"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
